### Exception

------

[TOC]

##### 01：异常处理机制

​	JVM 在执行代码的过程中若发现了一个异常，则会 new 一个异常对象，并将代码**整个堆栈信息封装到异常对象**中来表示错误信息，设置完毕后将该异常抛出，若抛出的语句被 try—catch 包围，则 JVM 会依次检查 catch 中是否有匹配该异常对象，若有则交给 catch 解决，否则会将异常抛出当前方法外，由方法的调用者解决。

- 作用：异常处理机制能让程序在错误发生时，按照代码的预先设定的异常处理程序，针对性地处理错误；

##### 02：处理异常的两种方式

- 使用 try…catch…finally 语句块处理它
- 在函数声明中使用 throws 声明交给函数调用者 (caller) 去解决
- try 用于包围可能出错的代码，catch 用来捕获 try 中代码抛出的错误并解决
- Exception ：一切异常都可以处理，在最后一个catch中捕获Exception，避免因未捕获异常导致程序中断 
- 当多个catch捕获不同异常时，这些异常间存在继承关系，那么子类异常要在上，先行捕获，父类异常在下，从上到下开始匹配

```java
public static int test1() {
    int b = 0;
    try {
        System.out.println("try....");
        return b += 10;
    } catch (Exception e) {
        log.error("test1: " + e.getMessage());
    } finally {
        if (b > 0) {
            System.out.println("return 计算完，未返回："+b);
            // return 3;
        }
    }
    System.out.println("未执行...." + b + 1);
    return b + 10;
}
```

##### 03：throw、throws 的区别

###### throw：

​	在方法体中用于抛异常对象的关键字，当一个方法使用throw抛出异常时，就要在方法上使用throws声明该类异常抛出的类型，以通知调用者解决，**RuntimeException（非检查异常） 及其子类异常使用throw抛出时，不强制要求使用throws声明**，其他异常都是强制要求的，否则编译不通过；

###### throws：

​		用在方法的参数列表之后，后跟异常类型列表，仅仅对该方法所出现异常进行抛给调用者，并不处理这些异常 当调用一个含有throws声明异常抛出的方法时，编译器要求上层必须处理该异常，如果是main函数则抛给JVM

```java
private static void read(String s) throws IOException {
    // 直接把异常对象抛给调用者
    try {
        // ...
    } catch (Exception e) {
        throw new FileNotFoundException("文件不存在异常，找不到目标文件");
    }
}
```

##### 04：java.lang.Throwable 

- public class Throwable implements Serializable 
- Java 语言中所有错误 或 异常的父类
- 错误类（Error）+ 异常类（Exception）
  - Error：一般是指与虚拟机相关的问题，如系统崩溃，虚拟机错误，内存空间不足，方法栈溢出等
  - Exception：由于程序错误，用户非法输入，文件损坏等导致的异常

##### 05：异常 (Exception和Error) 的分类

​	受检异常（checked exceptions）和 不受检异常（unchecked exceptions）

- ###### CheckedException：受检异常
  
- 编译时会检查它，当程序中可能出现这类异常，要么用try-catch语句捕获它，要么用throws子句声明抛出它，否则编译不会通过，这种异常是可以预测的，RuntimeException 类及子类异常
  
- ###### UncheckedException：不受检异常
  
  - 编译器不要求强制处置的异常，包括运行时异常（RuntimeException与其子类）和错误（Error）

##### 06：常见的 RuntimeException

1. NULLpointerException :空指针异常 
2. ArrayIndexoutOfBoundsException :下标越界 
3. IllegalArgumentException :传递不合法的参数 
4. ClassCastException :对象强制转换时，不是实例的子类 
5. ClassNotFoundException ：指定的类找不到

##### 07：fianlly 块

​	在异常捕获机制的最后，可以直接跟在 try 块之后或者最后一个 catch 块之后，finally 块中的代码一定执行， 只要try执行，无论try块中的代码是否抛出异常都会执行。

1. try 块后面可以跟多个catch块，匹配顺序是从上向下，编写捕获的类型时必须同级或者逐渐变大不能减小,并且执行完一 个catch后跳出；

2. finally 主要做一些资源清理工作，如流的关闭，数据库连接的关闭等；

3. ###### finally 与return 见面 return让步；

4. 在catch最后加上Exception异常，做终极处理；

##### 08：含 throws 方法的重写原则

继承父类，重写父类一个含有 throws 异常抛出声明的方法时

- 不能抛出比父类更大的异常，处理不了

##### 09：异常的方法

- 异常最先发生的地方，叫做异常抛出点
- printStackTrace()：在stderr(在标准错误流)中输出异常堆栈，**此方法无论和是都不应该被调用**
- getMassage() ：获取异常描述，上层调用者可以调用此方法，获取下层的异常信息
- getCause()：获取导致该异常的原因，异常可以嵌套；
- getStackTrace()：获取堆栈信息；

##### 10：自定义异常：通常用来描述业务逻辑上的出现的问题，命名见名知意

1. 一般继承 RuntimeException；
2. 重写构造方法，加版本号；



